### ISSUE TITLE
Weekly Digest Mail

### ISSUE THREAD

**Issue by dimitrydhondt** [eeemarv/elas-heroku#1]
Is het mogelijk om een uitbreiding te maken waarbij groepen kunnen kiezen om een wekelijkse samenvatting van eLAS op mail te krijgen ?

In zo'n samenvatting zouden V/A, maar ook nieuws terecht kunnen komen uit de eLAS database.

Sommige groepen hebben een groot grondgebied, en zijn vragende partij om V/A op afstand uit te splitsen.

**Comment by dimitrydhondt** [comment]
Ideaal zou zijn sorteren op afstand van de woonplaats van de gebruiker.

**Comment by marttiphpbb** [comment]
We kunnen de saldo mail uitbreiden. (één mail voor recent vraag en aanbod, nieuws én je eigen saldo). Maar de huidige saldo kunnen gebruikers individueel uitschakelen. Misschien is dat niet de bedoeling? (risico dat leden zo buitengesloten geraken.)

**Comment by eeemarv** [comment]
We kunnen de saldo mail uitbreiden. (één mail voor recent vraag en aanbod, nieuws én je eigen saldo). Maar de huidige saldo kunnen gebruikers individueel uitschakelen. Misschien is dat niet de bedoeling? (risico dat leden zo buitengesloten geraken.)

**Comment by dimitrydhondt** [comment]
Als je al wekelijks een digest krijgt, lijkt het me onzinnig om nog aparte saldo-mails te krijgen ?

**Comment by marttiphpbb** [comment]
Inderdaad, daarom lijkt het me zinnig om de saldo mails uit te breiden. Maar saldo mails kunnen worden uitgezet door leden.

**Comment by dimitrydhondt** [comment]
Voorstel :

De gebruiker kan kiezen : saldo mail (standaard : uit) / lets mail (standaard : aan) / beide / geen van beide. Maar er gaat altijd exact 1 mail / week uit.

Wat denk je daarvan ?

**Comment by marttiphpbb** [comment]
Ik denk dat we het database schema intact moeten laten om compatibel te blijven met eLAS. De cron_saldo column in users is een boolean geworden met de omschakeling naar Postgres. (MySQL kent geen booleans) Dus je kan de gebruikers geen vier keuzes geven. Ik dacht: misschien kunnen we best een configuratie-waarde in de tabel config toevoegen. Dat raakt niet aan het schema. Die config-waarde kan iets zijn zoals  'schakel-saldo-mail-keuze-uit' (maar dan in het engels). Als die config 0 is, dan kunnen gebruikers kiezen of ze de saldo-mail (met berichten en nieuws) al dan niet ontvangen. Als de config-waarde 1 (of niet nul) is, dan ontvangen gebruikers zowieso altijd wekelijks de mail. Ze zien dan geen keuze in hun account-beheer. Dat lijkt me nuttig voor groepen die niet werken met een mailinglijst. 
User-coordinaten voor geocoding zouden gecached kunnen worden met Redis. De gratis Redis is niet persistent, maar kent niet veel uitval. Momenteel gebruik ik Redistogo, maar het geheugen is beperkt voor de gratis versie (5MB). Daarom zou ik overschakelen naar een andere die 25MB gratis  geeft. Wat ook niet veel is.

**Comment by dimitrydhondt** [comment]
Mogelijk moeten we niet te veel moeite meer steken in eLAS... Dus geo-coding er mogelijk over ?Heb jij trouwens ervaring met client-side javascript development ?
Wat denk je trouwens van mijn suggestie jQuery + Mustache.js ?
Angular is toch een behoorlijk beest, en ik denk dat er te veel afvaller zullen zijn, en dat de drempel dan te hoog wordt om een echt open-source project te bouwen...
Dimi 


     On Saturday, March 28, 2015 7:26 PM, marttiphpbb <notifications@github.com> wrote:
   

 Ik denk dat we het database schema intact moeten laten om compatibel te blijven met eLAS. De cron_saldo column in users is een boolean geworden met de omschakeling naar Postgres. (MySQL kent geen booleans) Dus je kan de gebruikers geen vier keuzes geven. Ik dacht: misschien kunnen we best een configuratie-waarde in de tabel config toevoegen. Dat raakt niet aan het schema. Die config-waarde kan iets zijn zoals 'schakel-saldo-mail-keuze-uit' (maar dan in het engels). Als die config 0 is, dan kunnen gebruikers kiezen of ze de saldo-mail (met berichten en nieuws) al dan niet ontvangen. Als de config-waarde 1 (of niet nul) is, dan ontvangen gebruikers zowieso altijd wekelijks de mail. Ze zien dan geen keuze in hun account-beheer. Dat lijkt me nuttig voor groepen die niet werken met een mailinglijst. 
User-coordinaten voor geocoding zouden gecached kunnen worden met Redis. De gratis Redis is niet persistent, maar kent niet veel uitval. Momenteel gebruik ik Redistogo, maar het geheugen is beperkt voor de gratis versie (5MB). Daarom zou ik overschakelen naar een andere die 25MB gratis geeft. Wat ook niet veel is. —

**Comment by marttiphpbb** [comment]
Even een kleine correctie: MySQL kent klaarblijkelijk tegenwoordig wel booleans : BIT(1), maar in eLAS was het zoals algemeen toegepast een integer. 

Geocoding te veel moeite: dat is mogelijk. Ik zal de weekly digest zeker implementeren, dat is niet moeilijk. Geocoding zien we wel. Misschien leuk als voorstudie voor het project.

Angular + Mustache : is hier wat off-topic, we zitten in de issue-tracker. Ik stuur een mailtje.

**Comment by marttiphpbb** [comment]
Een eerste versie is klaar. De saldo-mail is uitgebreid met recent vraag en aanbod, nieuws, overzicht van nieuwe leden en uitstappende leden en recente transacties. Dus feitelijk is het een overzicht van alles wat gaande is. Zowel een text als html versie wordt verzonden. In de mail staan een hoop links die terugkoppelen naar eLAS. Want dat is ook een nieuwe feature: redirect after login. Dus, als je een link volgt naar een pagina in eLAS en er is nog geen sessie, dan wordt je eerst omgeleid naar de login-pagina. Wanneer de login succesvol is, kom je op de pagina van de link terecht. Het aantal dagen van de saldomail kan je in de instellingen bepalen (saldofreqdays). Dat was al zo. Dan is er een extra instelling 'forcesaldomail': als je die op 1 zet, krijgt iedere actief lid de saldo mail. Ik stuur je een voorbeeld van de mail.
