### ISSUE TITLE
Toevoegen maxlimit an export gebruikers

### ISSUE THREAD

**Issue by FrankDhondt** [eeemarv/elas-heroku#11]

**Comment by eeemarv** [comment]
Kan je het wat uitleggen?

**Comment by FrankDhondt** [comment]
in het admin gedeelte is er een mogelijkheid om gebruikers te exporteren. In de CSV file die dit genereert zit enkel de ondergrens van de rekening van een individuele gebruiker. We zouden hierin ook de bovengrens van de individuele gebruikers willen krijgen. Zo kunnen we een overzicht krijgen wie er een van de standaard afwijkende boven- en/of ondergrens heeft.

**Comment by eeemarv** [comment]
ok.
