### ISSUE TITLE
Vraag en aanbod laat negatieve nummers

### ISSUE THREAD

**Issue by retmarut** [eeemarv/elas-heroku#22]
Bij het aanmaken of wijzigen van v&a is het toegestaan om een negatieve "Geldigheid in dagen" en "Aantal rotskes" in te stellen.

Bij het wegschrijven wordt de geldigheid in dagen dan uiteindelijk op 0 gezet. Het negatieve aantal rotkses blijft evenwel behouden.

Oplossing: het niet toelaten dat deze velden op 0 of minder ingesteld kunnen worden.

**Comment by eeemarv** [comment]
Is opgelost.
