### ISSUE TITLE
Openstreetmap kaartje op gebruikerspagina

### ISSUE THREAD

**Issue by retmarut** [eeemarv/elas-heroku#25]
Om de afstand tot de ingelogde letser en de letser die mogelijk een interessant vraag/aanbod heeft af te toetsen speelt soms de afstand een rol; nabijheid blijft een sleutel.

Een kaartje bijvoegen op de gebruikerspagina naar keuze is de suggestie hier. OSM en geliëerde vrienden hebben API waar je afgaand op het adres een kaartje met een prikkertje kan oproepen.

Privacy-technisch lijkt het me redelijk, met het precieze adres de Lon-Lat wat te fuzzen zodat het prikkertje niet precies bij de mens thuis komt te staan. 500 meter diameter voor de willekeur... Een quasi-precies kaartje voor al degenen die hun adres publiek hebben staan, voor de rest valt het prikkertje in het hart van de postcode/district.

**Comment by eeemarv** [comment]
Het lijkt me beter enkel een kaartje te tonen wanneer het adres zichtbaar is. Een marker midden in het postcode-gebied kan alleen maar voor verwarring zorgen.
