### ISSUE TITLE
Standaard geldigheid in dagen

### ISSUE THREAD

**Issue by retmarut** [eeemarv/elas-heroku#26]
De default voor "Geldigheid in dagen" tijdens het aanmaken van nieuw vraag/aanbod mag gezet worden. Dat maakt leven een klein beetje gemakkelijk

* 90 voor de ene groep 300 voor de andere. 

da's hier een config-dinges

**Comment by eeemarv** [comment]
Ok, kijk bij de instellingen onderaan.
