### ISSUE TITLE
Single quote in gebruikersnaam geeft problemen

### ISSUE THREAD

**Issue by FrankDhondt** [eeemarv/elas-heroku#4]
Na inggave wordt dubbel quote getoond en bij volgende aanpassing van de gebruiker wordt de quote en alles erachter niet getoond in het edit veld.
Zie gebruiker LD0112 in eLas letsdurme.

**Comment by marttiphpbb** [comment]
Kreeg je een notificatie mail dat issue gesloten is? Het zou in orde moeten zijn nu.
