### ISSUE TITLE
Incorrect interlets limit error on non interlets transaction

### ISSUE THREAD

**Issue by FrankDhondt** [eeemarv/elas-heroku#9]
Onderstaande situatie deed zich ergens na 19u30 voor vandaag. De persoon LD0053 naar wie er overgeschreven word zit boven zijn limiet. De foutmelding spreekt echter over interlets en is niet duidelijk genoeg.

Elas geeft de foutmelding: De interletsrekening heeft zijn maximum limiet bereikt.

Ik deed Nieuwe transactie
Ik vulde de letscode, het aantal pluimen en de dienst in
En klikte op overschrijven.

Nadien kreeg ik onderstaand scherm en was mijn letscode ook verdwenen.

Dit was de tweede overschrijving die ik wou uitvoeren, de eerste naar Davy voor 160 pluimen leek geslaagd.

Mijn huidige pluimenstand is -113 en de limiet -600 daar zou het dus niet aan liggen.
Met interletsen heeft deze transactie evenmin iets te maken.
Kuren van eLas?

Mvg Jo

![image](https://cloud.githubusercontent.com/assets/12109288/8289216/43133694-191b-11e5-9c89-e96e1b2a7827.png)

**Comment by eeemarv** [comment]
De foutmelding is verkeerd. Deze moet zijn: 
'De bestemmeling heeft zijn limiet bereikt'.
Dat klopt, want LD0053 zit boven haar limiet.
Ik pas de foutmelding aan.

**Comment by eeemarv** [comment]
Opgelost:
* Juiste foutmelding.
* Het 'Van LETS code' veld blijft nu zijn waarde behouden (bij foutmelding).
